### ISSUE TITLE
Aggiunta del predicato che calcola la media degli elementi di una lista

### ISSUE THREAD

**Issue by Soapfedan** [Biuni/Prolog-AI#1]
%% //////////////////////////////////////////////////////////////////////////

% --------------------
% ** MEDIA DI UNA LISTA **
% --------------------
% Calcola la media di una lista
%
% INPUT: 	avg([1,3,5],A).
% OUTPUT:	A = 3.
%

average([],0).
average( List, Avg ):- 
    sum( List, Sum ),
    length( List, Length), 
    Avg is Sum / Length.

sum([],0).
sum([H|L],C):-
 sum(L,C0),
 C is C0 + H.

**Comment by Biuni** [comment]
Aggiunto. Thanks!
