### ISSUE TITLE
Aggiunta del predicato di conversione di una lista di interi in un numero

### ISSUE THREAD

**Issue by Soapfedan** [Biuni/Prolog-AI#2]
%% //////////////////////////////////////////////////////////////////////////

% --------------------
% ** CONVERSIONE DI UNA LISTA IN UN NUMERO **
% --------------------
% Converte una lista di interi in un numero
%
% INPUT: 	l_to_n([2,5,8,7,5,1],N).
% OUTPUT:	N = 258751.
%

l_to_n(L,N) :-
    l_to_n(L,0,N).

l_to_n([H|T],A,N) :-
    !,
    B is A*10+H,
    l_to_n(T,B,N).
l_to_n(_,N,N).

**Comment by Biuni** [comment]
Aggiunto. Thanks!
